### ISSUE TITLE
andel_kle_1 defaults to 100

### ISSUE THREAD

**Issue by amfollan** [geco-nhm/nin-qgis-plugin#43]
"Apply default value on update" should be unchecked in "andel_kle_1".

**Comment by peterhor** [comment]
This is now fixed in commit [af75cc2](https://github.com/geco-nhm/nin-qgis-plugin/commit/af75cc2dab12a5238dfd3cd3745649bf0a3ab236).
Flag for toggle apply on update is now implemented in code.
