### ISSUE TITLE
regdato defaults to now()

### ISSUE THREAD

**Issue by idammie** [geco-nhm/nin-qgis-plugin#46]
The date should be changed manually instead to keep date for when the mapping was done. Another option is to make another date-column for when the data is edited.

**Comment by peterhor** [comment]
This is now fixed in commit [af75cc2](https://github.com/geco-nhm/nin-qgis-plugin/commit/af75cc2dab12a5238dfd3cd3745649bf0a3ab236).
Flag for toggle apply on update is now implemented in code. The date `now()` will be only set the first time the polygon was created
